### ISSUE TITLE
Testing this with my 2019 leaf it seems to have issues.

### ISSUE THREAD

**Issue by kayak01** [KalenXI/NissanConnect#2]
python3 ./nissan.py get_vehicle_info -u jason@kates.org -p 'password' -pin #### -vin DELETED
usage: nissan.py [-h]
                 {start,stop,lock,unlock,horn_light,light_only,get_vehicle_info}
                 ...
nissan.py: error: unrecognized arguments: 3399

or if I run start I have the following error:
{"status":403,"message":"Forbidden","code":"CV40300","faultInfo":["Service not subscribed ","SERVICE_NOT_SUBSCRIBED"],"faultId":"e806c77c-4d78-41ea-93cf-b65307e59d07","language":"en_US"}

I have enough of a subscription to start the climate control remotely.  Thus the start might not be the same as starting the car.

**Comment by KalenXI** [comment]
Are you able to use the NissanConnect Services app to control your car? This script uses the same protocol as that app but I believe Nissan uses an entirely different app/protocol for the Leaf.
