### ISSUE TITLE
Looking for some advice if you dont mind 

### ISSUE THREAD

**Issue by bburroughs** [KalenXI/NissanConnect#3]
Hi, 

In your experience with HA, do you think its possible to create templates for each action Nissan connect can do (start, lock, unlock, etc) that pass the related variables to the python script you have to basically be able to create buttons for each action? Is that possible? 

Thanks

**Comment by KalenXI** [comment]
I would imagine so. Personally I do all my HA automation through Node Red and use the iOS actions to trigger the script. But I don't see why you couldn't do the same thing with HA templating and the HA shell component provided you have the necessary python packages installed on your HA system.
