### ISSUE TITLE
Account_ID

### ISSUE THREAD

**Issue by JohnQ86** [KalenXI/NissanConnect#4]
Hi, 

To do some testing, I run the script in an Ubuntu terminal but I have this error: 

KeyError: 'account_id'

How is generated this 'account_id' ?

Thanks

**Comment by KalenXI** [comment]
It's returned by the NissanConnect server when the script logs in with your username and password.

**Comment by JohnQ86** [comment]
Ok, so where the account_id error come from? Is the username and the password should be between quotes?

**Comment by KalenXI** [comment]
If your password contains spaces and/or special characters then probably. Here's how I run it:

`python3 /share/nissan.py lock -u email@gmail.com -p password -vin ABC0123456789 -pin 0000`

**Comment by JohnQ86** [comment]
Do you use Canada version of NissanConnect services? 

I always receive this error:
-status 500
-Internal Server processing error, Recoverable
-code CV50001

**Comment by KalenXI** [comment]
No, I've only tried it with the US version.

**Comment by JohnQ86** [comment]
I found what i'm doing wrong. As I'm in Canada, I should use NISNCIVCS instead of NISNNAVCS before the username and I should use cv.nissan.connect.ca.android.25.

Thanks again. You could close this issue.

**Comment by KalenXI** [comment]
Thanks. Glad you figured it out.
